template:
  - sensor:
      - name: "heatpump_json"
        unique_id: "heatpump_json"
        unit_of_measurement: "kWh"
        state_class: measurement
        state: "{{ states('sensor.heatpumpdaily')|float }}"
        attributes:
          state: "{{ states('switch.manualboiler') }}"
          power: "{{ (((states('sensor.eastron_sdm_total_power')) | float) * 1000)|round(1) }}"
          energy: "{{ ((states('sensor.eastron_sdm_import_active_energy')) | float) |round(1) }}"
          current_temp: "{{ states('sensor.ebusd_ctlv2_hwcstoragetemp_tempv')|round(1)}}"
          target_temp: "{{ states('number.ebusd_ctlv2_hwctempdesired_tempv') }}"
          unique_id: "000003"          
